replicaCount: 1

global:
  librechat:
    existingSecretName: "librechat-secrets"

image:
  registry: registry.totalsoft.local
  repository: librechat-custom
  tag: latest
  pullPolicy: Always

# This will be populated from the command line, but you can also set it manually here
imagePullSecrets: []
# - name: regcred

librechat:
  existingConfigYaml: "librechat-config"
  
  configEnv:
    NODE_ENV: "production"
    ALLOW_PASSWORD_RESET: "true"
    SEARCH: "true"
    ALLOW_EMAIL_LOGIN: "false"
    ALLOW_REGISTRATION: "false"
    ALLOW_SOCIAL_LOGIN: "true"
    ALLOW_SOCIAL_REGISTRATION: "false"
    APP_TITLE: "Librechat"
    CUSTOM_FOOTER: "Provided with ❤️"
    DEBUG_CONSOLE: "true"
    DEBUG_LOGGING: "true"
    DEBUG_OPENAI: "true"
    DEBUG_PLUGINS: "true" 
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    OPENID_CALLBACK_URL: "/oauth/openid/callback"
    OPENID_SCOPE: "openid profile email"
    OPENID_AUTO_REDIRECT: "true"
    DEBUG_OPENID_REQUESTS: "true"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false #error if set to true with the api version, needs to be fixed in the main branch
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: librechat.totalsoft.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: totalsoft-wildcard-tls
      hosts:
        - librechat.totalsoft.local

mongodb:
  enabled: false

vectordb:
  enabled: false

meilisearch:
  enabled: false

rag_api:
  enabled: false

nodeSelector:
  kubernetes.io/os: linux
