const express = require('express');
const fs = require('fs').promises;
const path = require('path');

const router = express.Router();

const SUPPORTED_LANGS = ['en', 'ro'];
const DEFAULT_LANG = 'en';

// Get docs directory for a given language
const getDocsPath = (lang) => {
  const safeLang = SUPPORTED_LANGS.includes(lang) ? lang : DEFAULT_LANG;
  return path.join(__dirname, '..', '..', '..', 'docs', 'user-guide', safeLang);
};

// Load sections metadata from sections.json generated by parse_docx.py
const loadSectionsMeta = async (lang) => {
  const metaPath = path.join(getDocsPath(lang), 'sections.json');
  try {
    const raw = await fs.readFile(metaPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
};

// Validate that a docId is a safe slug (no path traversal)
const isSafeDocId = (docId) => /^[a-z0-9-]+$/.test(docId);

// Extract subsections (## and ###) from markdown content
const extractSections = (content) => {
  const sections = [];
  let currentSection = null;
  for (const line of content.split('\n')) {
    const match = line.match(/^(#{2,3})\s+(.+)$/);
    if (match) {
      const level = match[1].length;
      const title = match[2];
      const id = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      if (level === 2) {
        currentSection = { id, title, subsections: [] };
        sections.push(currentSection);
      } else if (level === 3 && currentSection) {
        currentSection.subsections.push({ id, title });
      }
    }
  }
  return sections;
};

/**
 * GET /api/docs
 * Get list of all documentation sections.
 * Query params:
 *   lang — 'en' (default) or 'ro'
 */
router.get('/', async (req, res) => {
  try {
    const lang = SUPPORTED_LANGS.includes(req.query.lang) ? req.query.lang : DEFAULT_LANG;
    const meta = await loadSectionsMeta(lang);

    if (!meta) {
      return res.status(503).json({
        error: 'Documentation not yet generated. Run: bash custom/scripts/generate_help.sh',
      });
    }

    res.json({
      sections: meta.sections,
      default: meta.default || (meta.sections[0] && meta.sections[0].id) || 'index',
      lang,
      supportedLangs: SUPPORTED_LANGS,
    });
  } catch (error) {
    console.error('Error listing docs:', error);
    res.status(500).json({ error: 'Failed to list documentation sections' });
  }
});

/**
 * GET /api/docs/:docId
 * Get content of a specific documentation section.
 * Query params:
 *   lang — 'en' (default) or 'ro'
 */
router.get('/:docId', async (req, res) => {
  try {
    const { docId } = req.params;
    const lang = SUPPORTED_LANGS.includes(req.query.lang) ? req.query.lang : DEFAULT_LANG;

    if (!isSafeDocId(docId)) {
      return res.status(400).json({ error: 'Invalid document ID' });
    }

    const meta = await loadSectionsMeta(lang);
    if (!meta) {
      return res.status(503).json({
        error: 'Documentation not yet generated. Run: bash custom/scripts/generate_help.sh',
      });
    }

    const sectionMeta = meta.sections.find((s) => s.id === docId);
    if (!sectionMeta) {
      return res.status(404).json({ error: 'Documentation section not found' });
    }

    const filePath = path.join(getDocsPath(lang), sectionMeta.filename);
    const content = await fs.readFile(filePath, 'utf-8');
    const sections = extractSections(content);

    res.json({
      id: docId,
      title: sectionMeta.title,
      filename: sectionMeta.filename,
      content,
      sections,
      lang,
    });
  } catch (error) {
    console.error('Error reading doc:', error);
    if (error.code === 'ENOENT') {
      res.status(404).json({ error: 'Documentation file not found' });
    } else {
      res.status(500).json({ error: 'Failed to read documentation' });
    }
  }
});

module.exports = router;
